version: '3.8'
services:
    database:
        container_name: db
        build:
            context: .
            dockerfile: .docker/db/Dockerfile
        env_file:
            - .env
        ports:
            - '${MYSQL_PORT}:${MYSQL_PORT}'
        volumes:
            - .:/opt/app/api
        command: [ '--log_bin_trust_function_creators=1', '--max_connections=1000']
    cache:
        container_name: cache
        image: redis:7.0.7-alpine
        restart: always
        env_file:
            - .env
        ports:
            - '${REDIS_PORT}:${REDIS_PORT}'
        command: redis-server --save 20 1 --loglevel warning --requirepass '$REDIS_PASS'
        volumes:
            - cache:/data
volumes:
    cache:
        driver: local
